### ISSUE TITLE
eboxbw fails on the first hour of the first day of the month

### ISSUE THREAD

**Issue by eepp** [eepp/eboxbw#2]
This is because no data for the month is available at that time.

**Comment by eepp** [comment]
Traceback:

```
Traceback (most recent call last):
  File "/usr/bin/eboxbw", line 9, in <module>
    load_entry_point('eboxbw==2.0', 'console_scripts', 'eboxbw')()
  File "/usr/lib/python3.4/site-packages/eboxbw/cli.py", line 183, in run
    _main(args)
  File "/usr/lib/python3.4/site-packages/eboxbw/cli.py", line 165, in _main
    raise e
  File "/usr/lib/python3.4/site-packages/eboxbw/cli.py", line 151, in _main
    usage_info = eboxbw.get_usage_info(args.id)
  File "/usr/lib/python3.4/site-packages/eboxbw/eboxbw.py", line 330, in get_usage_info
    return _get_usage_info_from_page(_download_page(id))
  File "/usr/lib/python3.4/site-packages/eboxbw/eboxbw.py", line 322, in _get_usage_info_from_page
    cur_month_usage = _get_cur_month_usage(soup)
  File "/usr/lib/python3.4/site-packages/eboxbw/eboxbw.py", line 308, in _get_cur_month_usage
    date = day_usages[0].date.replace(day=1)
IndexError: list index out of range
```
